server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=app_data_base;loginTimeout=30;
    username: sa
    password: yourStrong(!)Password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

mybatis:
  config-location: classpath:mybatis-config.xml

